# Generated by Django 3.0.3 on 2020-03-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contact_no', models.CharField(max_length=13)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
