# Generated by Django 3.0.3 on 2020-03-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField(max_length=5)),
                ('floor', models.IntegerField(max_length=3)),
            ],
        ),
    ]
