# Generated by Django 3.0.3 on 2020-03-26 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20200326_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('checkin', models.DateField()),
                ('cnic', models.CharField(max_length=13, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('desc', models.CharField(max_length=1000)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='service_desc',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='rooms',
            name='booking',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.Booking'),
        ),
    ]
