# Generated by Django 3.0.3 on 2020-04-18 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20200327_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
        migrations.AddField(
            model_name='services',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
    ]
