# Generated by Django 3.0.3 on 2020-04-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20200418_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='isPaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='totalAmount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=12),
        ),
    ]
