# Generated by Django 3.0.3 on 2020-04-19 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20200418_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayByCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('nameOnCard', models.CharField(max_length=30)),
                ('cardNo', models.DecimalField(decimal_places=0, max_digits=20)),
                ('expMonth', models.CharField(max_length=10)),
                ('expYear', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='isPaid',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('totalAmount', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('paidAmount', models.DecimalField(decimal_places=2, default='0', max_digits=12)),
                ('PayByCard', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.PayByCard')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Payment'),
        ),
    ]
