# Generated by Django 3.0.3 on 2020-04-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20200419_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paybycard',
            name='cardNo',
            field=models.CharField(max_length=20),
        ),
    ]
