# Generated by Django 3.0.3 on 2020-04-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20200419_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(blank=True, to='app1.Services'),
        ),
    ]
