# Generated by Django 3.0.3 on 2020-04-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_payment_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cnic',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
