# Generated by Django 3.0.3 on 2020-04-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20200419_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='checkout',
            field=models.DateField(null=True),
        ),
    ]
